global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'aspnetcore_api'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:7005']
